spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
server:
  port: 3355

eureka:
  instance:
    hostname: eureka6001 #服务器的实例名称
  client:
    register-with-eureka: false #表示是否向eureka注册中心注册
    fetch-registry: false #表示自己是注册中心
    service-url:
      defaultZone: http://localhost:6001/eureka/

---
spring:
  profiles: test
server:
  port: 3355

eureka:
  instance:
    hostname: eureka6001 #服务器的实例名称
  client:
    register-with-eureka: false #表示是否向eureka注册中心注册
    fetch-registry: false #表示自己是注册中心
    service-url:
      defaultZone: http://localhost:6001/eureka/